In [1]:
import numpy as np

In [2]:
# 3slide 3row 3col
# reshape is a function which changes object 

a = np.arange(3*3*3).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
# properties/attributes are method which doesnot change object

# no. of dimensions/rank 3D => real world data max 5-Dim(video)
print(a.ndim)

# no. of axis in each dimension
print(a.shape)

# no. elements
print(a.size)

3
(3, 3, 3)
27


In [6]:
# 4 pics resolution 8x8
# 1) samples
# 2) rows
# 3) columns

t = np.arange(4*8*8).reshape(4,8,8)  
t

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]],

       [[128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [7]:
# min value
# max value
# shape(sample, rows, cols)
np.random.randint(0,255,(10,8,8)) 

array([[[133, 222, 219,  86, 135,  69, 243, 166],
        [ 26,  70,  52, 250,  23, 193, 206,  19],
        [128, 228, 101,  20, 241,  62,  11, 170],
        [250, 105, 214,  89, 234,  33,  53, 109],
        [141, 214, 172, 104, 107,  63,  38, 185],
        [109, 119, 102, 184, 177, 236, 241, 130],
        [ 77, 135,  53, 167, 222, 141, 112, 118],
        [ 97, 212, 105, 103, 118, 231,  40, 177]],

       [[  8, 106, 253,  24,  80,  27,  89,  41],
        [153,  12, 203, 114, 227, 112, 182, 152],
        [ 57, 153, 235, 103, 248,  83, 175, 254],
        [206, 209, 134, 215, 182,  93, 251, 164],
        [194, 160,  86, 112,  76,  80, 217,  26],
        [ 95, 118, 177, 227,  92, 226, 175, 227],
        [ 97, 241, 198, 219,  15, 226, 101,  28],
        [ 82,  74,  60, 192, 212,  57,  36, 218]],

       [[204,   2, 177,  79,  51,  17, 106, 190],
        [ 35,  17, 138, 183, 233, 132, 136, 129],
        [136,  25, 161, 184,  68,  29,  60, 220],
        [120,  89,  77, 171,  25,  89, 132, 15

In [3]:
b = np.arange(100).reshape(10,10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [11]:
# create numpy array
n1 = np.array([1,2,3])
print(n1)
display(n1)

[1 2 3]


array([1, 2, 3])

In [10]:
n2 = np.array((1,2,3))
print(n2)
display(n2)

[1 2 3]


array([1, 2, 3])

In [17]:
n3 = np.array([[1,2,3],
             [4,5,6]])
display(n3)
print(n3[0])
print(n3[1])
# print(n3[2]) error
print(n3.shape)
print(n3[:,-2:])

array([[1, 2, 3],
       [4, 5, 6]])

[1 2 3]
[4 5 6]
(2, 3)
[[2 3]
 [5 6]]


# How to create a basic array

* np.array()
* np.zeros()
* np.ones()
* np.empty()
* np.arange()
* np.linspace()

In [20]:
display(np.zeros(10))  # returns array of zero
display(np.ones(10))   # returns array of one
display(np.empty(10))  # returns garbage value

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
# steps
np.linspace(1,2,5) # start, end, stepsize

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
np.linspace(1,60,3)

array([ 1. , 30.5, 60. ])

In [27]:
x = np.arange(3*3*3).reshape(3,3,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
# copies shape of one array and fill it with one
np.ones_like(x)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [30]:
# copies shape of one array and fill it with zero
np.zeros_like(x)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [31]:
# copies shape of one array and fill it with one
np.empty_like(x)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [32]:
np.ones((10,10),dtype='str')

array([['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1']], dtype='<U1')

# sorting

In [35]:
arr = np.array([92,4,1,34,87,2,5,7])
np.sort(arr)

array([ 1,  2,  4,  5,  7, 34, 87, 92])

In [39]:
# any one dim
np.arange(3*3*3).reshape(3,3,-1) # when we don't know any argument we call fill it with -1, it fills itself

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [40]:
# any one dim
np.arange(3*3*3).reshape(3,-1,3) # when we don't know any argument we call fill it with -1, it fills itself

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [38]:
np.arange(3*3*3).reshape(-1,3,3) # when we don't know any argument we call fill it with -1, it fills itself

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### argfunc => perform function and returns corresponding index

In [41]:
a = np.array([1,7,20,0,4,3])

print(np.argmax(a))    # index of maximum value
print(np.argmin(a))    # index of minimum value
print(np.argsort(a))   # sort wrt index

2
3
[3 0 5 4 1 2]


In [47]:
labels = ['cat','dog','apple','orange']
prediction = [70,100,100,15]
index = np.argmax(prediction) # max index probability (returns index of first occurence of largest number)
print(labels[index])

dog


### concatenate

In [49]:
a = np.arange(1,11).reshape(5,2)
b = np.arange(11,21).reshape(5,2)
display(a)
display(b)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [55]:
np.concatenate((a,b))  # axis default 0

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [56]:
np.concatenate((a,b),axis=1)  

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [57]:
np.stack((a,b))   # axis default 0

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [58]:
np.stack((a,b),axis=1)

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]],

       [[ 5,  6],
        [15, 16]],

       [[ 7,  8],
        [17, 18]],

       [[ 9, 10],
        [19, 20]]])

In [59]:
# horizontal
np.hstack((a,b))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [60]:
# vertical
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

### axis

no. of dimensions
* sample
* row
* column

In [63]:
a = np.arange(2*2*2).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
a.sum()

28

In [65]:
display(a)
a.sum(axis=0) # slide wise add / overlap add

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 4,  6],
       [ 8, 10]])

In [66]:
display(a)
a.sum(axis=1) # row wise add

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 2,  4],
       [10, 12]])

In [67]:
display(a)
a.sum(axis=2) # column wise add

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 1,  5],
       [ 9, 13]])

### index, slicing, fancy slicing and boolean slicing 

In [70]:
a = np.arange(4*4).reshape(4,4)  # 2x2 matrix
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
# print in the form of text
print(a[0])
print(a[-1])

[0 1 2 3]
[12 13 14 15]


In [72]:
# display in the form of original format of data type
display(a)
display(a[0:2])  # end not included

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [73]:
display(a)
display(a[::2])  # stepsize

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [75]:
# fancy slicing
display(a)
display(a[[1,2,0,1,1,1]]) # we give index of rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7]])

In [79]:
# select even numbers
b = np.arange(1,7)
display(b)
c = b%2==0
display(b[c])

array([1, 2, 3, 4, 5, 6])

array([2, 4, 6])

In [80]:
# divisible by 2
display(a)
a[a%2==0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [81]:
# divisible by 2 and 4
display(a)
a[(a%2==0) & (a%4==0)]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([ 0,  4,  8, 12])

### deep and shallow copy

In [88]:
a = np.arange(4*4).reshape(4,4)
b = a
c = a.copy()

In [87]:
display(a)
display(b)
display(c)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [89]:
a[0][0]=200
display(a)
display(b)
display(c)

array([[200,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

array([[200,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### split

In [90]:
display(a)
# horizontal/ row wise
display(np.split(a,2))  # default axis = 0

array([[200,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

[array([[200,   1,   2,   3],
        [  4,   5,   6,   7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [92]:
display(a)
# vertical/ column wise
display(np.split(a,2,axis=1))

array([[200,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

[array([[200,   1],
        [  4,   5],
        [  8,   9],
        [ 12,  13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [93]:
display(np.split(a,4,axis=1))

[array([[200],
        [  4],
        [  8],
        [ 12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [94]:
np.vsplit(a,2)

[array([[200,   1,   2,   3],
        [  4,   5,   6,   7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [95]:
# horizontal
np.hsplit(a,2)

[array([[200,   1],
        [  4,   5],
        [  8,   9],
        [ 12,  13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [98]:
# broadcasting
a+1000000

array([[1000200, 1000001, 1000002, 1000003],
       [1000004, 1000005, 1000006, 1000007],
       [1000008, 1000009, 1000010, 1000011],
       [1000012, 1000013, 1000014, 1000015]])

In [ ]:
# ones
# zeros
# unique

In [ ]:
# data augmentation

In [ ]:
# top to bottom => axis = 0
# left to right => axis = 1